- name: google-dns
  host: 8.8.8.8
  port: 53
  proto: udp

- name: github-ssh
  host: github.com
  port: 22
  proto: tcp

- name: demo-web
  host: example.com
  port: 80
  proto: tcp
  l7_check:
    type: http
    path: /          # GET http://example.com/